# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('address', models.CharField(max_length=30, verbose_name='地点')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('truename', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('xueke', models.CharField(max_length=30, verbose_name='xueke')),
                ('typefs', models.CharField(max_length=20, verbose_name='学院')),
                ('labnumber', models.CharField(max_length=50, verbose_name='实验室名称')),
                ('zhiwu', models.CharField(max_length=50, verbose_name='职务')),
                ('zhicheng', models.CharField(max_length=50, verbose_name='职称')),
                ('tel', models.CharField(max_length=50, verbose_name='联系电话')),
                ('tel_office', models.CharField(max_length=50, verbose_name='办公电话')),
                ('eamil', models.CharField(max_length=50, verbose_name='邮箱')),
            ],
        ),
    ]
