# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eamil',
            field=models.CharField(max_length=50, verbose_name='邮箱'),
        ),
    ]
